### ISSUE TITLE
Cannot assign to read only property 'name' of function 'function Constructor

### ISSUE THREAD

**Issue by erictraub** [One-com/node-httperrors#4]
I started getting this error recently.  I believe that it is from the library `createerror` that is a dependency.  How can I fix it?

```
TypeError: Cannot assign to read only property 'name' of function 'function Constructor(messageOrOptionsOrError, preserveError) {
            if (preprocess) {
                va...<omitted>... }'
    at createError (/home/dev/web-node-server/server/node_modules/createerror/lib/createError.js:125:13)
    at Object.<anonymous> (/home/dev/web-node-server/server/node_modules/httperrors/lib/HttpError.js:48:34)
    at Module._compile (module.js:571:32)
    at loader (/home/dev/web-node-server/server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dev/web-node-server/server/node_modules/babel-register/lib/node.js:154:7)
```

**Comment by papandreou** [comment]
Thanks for getting in touch!

I couldn't reproduce the problem myself (it might depend on a specific version of node or something else), but I vaguely remember a similar problem where using `Object.defineProperty` to override a function name worked fine, as opposed to just changing `fn.name`.

I've attempted a fix here: https://github.com/One-com/node-createerror/commit/f6b09ec53061f6c359d516a0f048da22b49a5e11

It's included in httperrors 2.3.0 -- could you try that and see if it helped?

**Comment by gustavnikolaj** [comment]
Closing this issue assuming that the above fix by @papandreou adressed the issue. Let us know if that's not the case!

**Comment by alexjeffburke** [comment]
We are using `createerror` in the browser and have just lived through some consequences of this that I think should be documented. Please consider the commentary below`"in the browser"`.

Without this change, it appears that you get the error mentioned by the original reporter if you happen to bundle this code in *strict* mode - unfortunately at least `rollup` will add the "use strict" pragma by default when doing an ES6 module to UMD build.

The `Object.defineProperty` fix is arguably worse though - it breaks hard on Safari version 9 (meaning on iOS 9 and macOS 10.9-10.11) causing it to throw "TypeError: Attempting to change value of a readonly property.". If this version is required by httpErrors I'd assume it has also now inherited this problem.
